name: Tests unitaires - Main
description: Exécute les tests unitaires lorsqu'un push est effectué sur la branche main.
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v2
      
      - name: Compilation du code
        run: make
      
      - name: Exécution des tests
        run: ./minishell
